spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/my_agent?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000

server:
  port: ${SERVER_PORT:8081}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  level:
    space.huyuhao.myoj: info
